### ISSUE TITLE
Installation on Arch Linux

### ISSUE THREAD

**Issue by AntonMeep** [dlang-snaps/dmd.snap#11]
Why this snap is not published yet? [Instructions](https://snapcraft.io/docs/build-snaps/publish) are pretty simple, or are there other problems?

As package for Archlinux got orphaned, I am looking for alternatives and snap package is the best one.

**Comment by WebDrake** [comment]
@ohdatboi the snap is published in the store, but only in the `edge` and `beta` channels, since there is an outstanding issue with `rdmd`.

You can install with, for example:

```
sudo snap install --classic --beta dmd
```

**Comment by AntonMeep** [comment]
> sudo snap install --classic --beta dmd

It doesn't work.

```
error: cannot install "dmd": snap not found
```

But this works:
```
sudo snap install --classic --edge dmd
```

And results in:
```
error: cannot install "dmd": classic confinement is not yet supported on your distribution
```
Maybe they'll add support of classic packages on archlinux later. 
Anyway, thank you so much.

> there is an outstanding issue with rdmd

What kind of issue?

**Comment by WebDrake** [comment]
Ah, I'm sorry: I should have said `edge`, indeed.  I'd forgotten I hadn't pushed to `beta` for `dmd` yet.

> Maybe they'll add support of classic packages on archlinux later.

Yes, I'm afraid Arch's `snapd` package doesn't yet support classic confinement, and without that it's really not viable to use the `dmd` snap (or any of the D compiler/dev-tool snaps, for that matter).  I imagine it will be addressed at some point, but I'm afraid it's not something I have any influence over :-(

The distros the snap package is known to work on are Ubuntu, Debian and OpenSUSE.

Can I just confirm (for the record) what `snapd` version you have on your Arch install?

> What kind of issue [with rdmd]?

There's a rather interesting issue with the `AppArmor` rules that are created for the snap package, which blocks the compiler `rdmd` invokes from inheriting the file-descriptors associated with a file `rdmd` creates in `/tmp`.  In other words, it's a bug in `snapd` (more here: https://forum.snapcraft.io/t/failed-to-flush-stdout-permission-denied/485), but one which impacts strongly on the usability of the `dmd` snap package.

I am somewhat tempted to cut `rdmd` from the package until it's possible to deal with that.  Otherwise I'm effectively forced to hold back the wider release of the `dmd` snap package until that bug is addressed by the `snapd` developers.

**Comment by AntonMeep** [comment]
> Can I just confirm (for the record) what snapd version you have on your Arch install?
```
$ snap version  
snap    unknown
snapd   unknown
series  16
arch    unknown
kernel  4.11.9-1-ARCH
```
```
$ pacman -Qi snapd | grep Version
Version         : 2.26.1-1
```
> I imagine it will be addressed at some point, but I'm afraid it's not something I have any influence over

It's ok, I'll google for same issues on archlinux forums and in the snapd repository tomorrow.

**Comment by WebDrake** [comment]
> It's ok, I'll google for same issues on archlinux forums and in the snapd repository tomorrow.

Good luck!  I do care about good Arch support, so I will be pushing for classic support myself, but it is ultimately in the hands of the maintainers of the arch package.

**Comment by WebDrake** [comment]
This is a rather outdated response, but you should be able to install and use just fine on Arch now (I've done so successfully myself).  Can you confirm it works for you too (or let me know if it doesn't)?

**Comment by AntonMeep** [comment]
@WebDrake Indeed, it should install fine on Arch Linux. I can't confirm though: for some reason snapd was moved to AUR and I don't feel like building it.

Anyway, dmd now is well-maintained package so using snaps doesn't make much sense.
Thanks for all your effort since snaps are still useful in Ubuntu-like distros!

**Comment by WebDrake** [comment]
Well, I'm glad to hear that Arch users have options!  Thanks for checking in :-)
